#!/bin/bash

conf_path=$HOME/.config/jenapiclirc

if [ ! -e "$conf_path" ]; then
	echo "No config found at: $conf_path"
	exit 1
fi

. $conf_path

function usage() {
	echo Usage [-j job_name]:
	echo -e "\t$0 latest"
	echo -e "\t$0 detail [run_id]"
	echo -e "\t$0 console [run_id]"
}

while getopts "j:" opt; do
  case ${opt} in
    j)
        jenkins_job=$OPTARG
        ;;
    \? )
      usage
      exit -1
      ;;
  esac
done
shift $((OPTIND -1))


case $1 in
	latest)
		url="${jenkins_uri}/job/${jenkins_job}/lastCompletedBuild/api/json?tree=id"
		id=$(curl --silent --user "${user}:${api_key}" "$url" | jq .id)
		echo $id | tr -d '"'
		;;
	detail)
		id=$2
		url="${jenkins_uri}/job/${jenkins_job}/${id}/wfapi/describe"
	        text=$(curl --silent --user "${user}:${api_key}" "$url")
		echo $text | jq .
		;;
	console)
		id=$2
		url="${jenkins_uri}/job/${jenkins_job}/${id}/consoleText"
		curl --silent --user "${user}:${api_key}" "$url"
		;;
	*)
		usage
		;;
esac

